# What this file does
- Add Company nodes
- Apply Louvain to Company nodes and write the community id back to Company nodes
- Add corp_community_id property to Complaint nodes based on Companies' community ID

# Dependencies
#### Run the following file(s) before running this code.
- 03_baseline_similarity_graph.ipynb (or 03b or 03c)
- 07_gds_Louvain_Summary.ipynb
- 21_gds_Centrality_on-graph.ipynb

##### To add some nodes, this code is updating the data in Mongo, and then updating neo4j accordingly.

##### Note:
URL of the Neo4j browser:
- https://[IP address]:7473/browser/

ID & Pass: 
- Use the one in .env

In [1]:
# Config
DB_NAME:str         = "project03"
COLLECTION_NAME:str = "complaints"

In [2]:
import time
from datetime import datetime, timedelta

In [3]:
import os
import sys
import json
import numpy as np
import pandas as pd
from IPython.display import display
import tiktoken
import textwrap
import logging

# pretty print some of the Neo4j outputs
logger = logging.getLogger("neo4j")
logger.setLevel(logging.CRITICAL)

In [4]:
from dotenv import load_dotenv  
load_dotenv()

True

In [5]:
# from openai import OpenAI
import neo4j
from pymongo import MongoClient

In [6]:
# Ignore unclosed SSL socket warnings - optional in case you get these errors
import warnings

In [7]:
warnings.filterwarnings(action="ignore", message="unclosed", category=ResourceWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [8]:
# Show all columns
pd.set_option('display.max_columns', None)

# Show all rows
pd.set_option('display.max_rows', None)

In [9]:
# Timestamp (Start)
current_datetime = datetime.now()
formatted_time = current_datetime.strftime("%Y-%m-%d_%H:%M:%S")
print(formatted_time)

start_time = time.time()

2026-01-08_22:23:33

### Mongo

In [10]:
# Connect to the mongo database
# mongodb is the protocol; mongo is the hostname, which for us is the container name; 27017 is the TCP port number
mongo = MongoClient("mongodb://mongo:27017/")

In [11]:
# # Drop the database
# mongo.drop_database(DB_NAME)

In [12]:
# Access to the existing mongo database (this seems to be the same command with creating a new database)
db = mongo[DB_NAME]

In [13]:
# Connect to the existing collection (this seems to be the same command with creating a new collection)
collection = db[COLLECTION_NAME]

In [14]:
# An example of the data in mongo
collection.find_one()

{'_id': ObjectId('69609e65d00a36fd6bcd31e2'),
 'date_received': '06/05/25',
 'product': 'Credit reporting or other personal consumer reports',
 'sub_product': 'Credit reporting',
 'issue': 'Incorrect information on your report',
 'sub_issue': 'Information belongs to someone else',
 'consumer_complaint_narrative': 'I hope this complaint finds you well. I would like to follow up on the complaints I sent to your attention regarding certain items on my credit report. As of today, I have not received any communication or updates regarding the resolution of the disputes I sent to the bureaus. I understand that the investigation process takes time, but I would like to inquire about the current status and any progress made in resolving the issues outlined in my previous communication. The following are the items that I would like to be removed from my credit file. //',
 'company_public_response': 'Company has responded to the consumer and the CFPB and chooses not to provide a public response',
 'company': 'TRANSUNION INTERMEDIATE HOLDINGS, INC.',
 'state': 'IL',
 'zip_code': '60005',
 'date_sent_to_company': '06/05/25',
 'company_response_to_consumer': 'Closed with explanation',
 'complaint_id': 13926939,
 'embeddings': [0.032297533005476,
  0.0026959541719406843,
  0.021540675312280655,
  0.02973637543618679,
  -0.03200097754597664,
  -0.006055787205696106,
  -0.01962654665112495,
  -0.01543433777987957,
  0.03787815943360329,
  0.01659359782934189,
  0.03073387965559959,
  -0.01356738992035389,
  -0.03946876898407936,
  -0.02152719534933567,
  0.0095099788159132,
  0.03844430670142174,
  0.03755464404821396,
  0.02206638641655445,
  -0.031596582382917404,
  0.018992997705936432,
  0.028792791068553925,
  0.020731888711452484,
  -0.014126800000667572,
  -0.0055604055523872375,
  -0.034319497644901276,
  -0.018265090882778168,
  -0.013014718890190125,
  0.004694330506026745,
  0.008013724349439144,
  -0.020529691129922867,
  0.0035620296839624643,
  -0.0215002354234457,
  -0.0311652310192585,
  0.04076283052563667,
  0.05612976849079132,
  0.0695556178689003,
  -0.015339979901909828,
  -0.002805477473884821,
  0.024398386478424072,
  -0.013291054405272009,
  0.02197202667593956,
  0.03615274652838707,
  -0.004084370564669371,
  -0.028145762160420414,
  -0.045696426182985306,
  0.009503238834440708,
  -0.034885648638010025,
  -0.013196696527302263,
  -0.03305239975452423,
  0.030949555337429047,
  -0.020111819729208943,
  0.03111131303012371,
  0.00639615161344409,
  0.04270391538739205,
  0.005358208902180195,
  0.020920604467391968,
  0.017159748822450638,
  -0.0010421548504382372,
  0.010042429901659489,
  0.01720018871128559,
  -0.026649508625268936,
  0.016431841999292374,
  -0.010938834398984907,
  -0.021540675312280655,
  -0.03283672407269478,
  -0.00048021686961874366,
  0.00576260220259428,
  0.02017921768128872,
  -0.013466292060911655,
  0.010473782196640968,
  -0.011397146619856358,
  0.04140985757112503,
  0.031515706330537796,
  -0.031839221715927124,
  -0.021271079778671265,
  -0.005779452156275511,
  0.03642234206199646,
  -0.024020953103899956,
  0.023630039766430855,
  0.01997702196240425,
  -0.030706919729709625,
  0.0031020324677228928,
  -0.05726207047700882,
  -0.0034676711075007915,
  0.011882418766617777,
  0.0203274954110384,
  -0.05348773300647736,
  0.002006801078096032,
  0.0248971376568079,
  -0.03391510620713234,
  -0.0494438000023365,
  0.03701545298099518,
  -0.02863103523850441,
  0.01582525111734867,
  -0.02214726433157921,
  -0.028792791068553925,
  -0.0429195910692215,
  0.007777828257530928,
  0.006915122736245394,
  0.0444832444190979,
  0.011949817650020124,
  0.004455064423382282,
  -0.006281573325395584,
  -0.03170442208647728,
  0.025625046342611313,
  0.005176232196390629,
  0.026191195473074913,
  -0.01872340217232704,
  0.008802291005849838,
  -0.010197446681559086,
  -0.007501492742449045,
  0.003364888019859791,
  -0.05758558213710785,
  0.020017459988594055,
  -0.012711424380540848,
  0.018170731142163277,
  -0.08955959975719452,
  -0.003498000791296363,
  0.030518202111124992,
  -0.01240138988941908,
  -0.028253600001335144,
  0.018008975312113762,
  0.004977405536919832,
  -0.01776633784174919,
  0.00576260220259428,
  0.0023825496900826693,
  0.05211279541254043,
  -0.03747376427054405,
  -0.029278064146637917,
  -0.0269865021109581,
  0.023562639951705933,
  -0.009422359988093376,
  0.01128256879746914,
  -0.04019667953252792,
  -0.07780524343252182,
  0.014477274380624294,
  0.05173536390066147,
  -0.027687450870871544,
  -0.05168144404888153,
  -0.05898747965693474,
  0.005671613849699497,
  0.028577115386724472,
  0.012280072085559368,
  -0.002006801078096032,
  -0.021122802048921585,
  0.019478268921375275,
  0.029331982135772705,
  -0.017415864393115044,
  -0.019653506577014923,
  0.007953065447509289,
  0.009125805459916592,
  0.04278479516506195,
  -0.05502442643046379,
  0.019505228847265244,
  0.05151968449354172,
  -0.00639615161344409,
  0.02917022444307804,
  0.04672088846564293,
  -0.05138488858938217,
  -0.0031374169047921896,
  -0.06756061315536499,
  -0.01531301997601986,
  -0.0023050408344715834,
  -0.03677281737327576,
  0.059095319360494614,
  0.007535192184150219,
  0.016377922147512436,
  -0.00527733052149415,
  -0.03674585744738579,
  -0.028172722086310387,
  0.0119902566075325,
  -0.0334298312664032,
  -0.05817869305610657,
  -0.04507635533809662,
  -0.02322564646601677,
  0.002660569967702031,
  0.01698451116681099,
  0.006268093828111887,
  -0.012293551117181778,
  -0.01101971324533224,
  -0.02305040881037712,
  -0.0016487445682287216,
  0.02594855986535549,
  0.0009705435368232428,
  -0.05480875074863434,
  -0.02726957760751247,
  -0.054673951119184494,
  0.02194506861269474,
  0.00185515359044075,
  0.00797328446060419,
  0.05114225298166275,
  0.03979228436946869,
  0.012623805552721024,
  0.019842224195599556,
  -0.054646994918584824,
  -0.012172233313322067,
  0.0034154371824115515,
  0.0169305931776762,
  -0.02689214423298836,
  0.022915611043572422,
  -0.011956557631492616,
  -0.027566133067011833,
  -0.030949555337429047,
  0.032351452857255936,
  -0.06297749280929565,
  -0.04089762642979622,
  -0.01773937977850437,
  -0.007885666564106941,
  -0.01502994541078806,
  0.001321860123425722,
  0.02101496420800686,
  -7.845648360671476e-05,
  -0.0016209424939006567,
  0.059095319360494614,
  -0.08379025757312775,
  -0.04804190620779991,
  -0.023481762036681175,
  0.009766094386577606,
  -0.016162246465682983,
  -0.02172939106822014,
  0.05108833312988281,
  0.036233626306056976,
  0.024533184245228767,
  0.03671889752149582,
  0.010696198791265488,
  0.09371136873960496,
  0.015865691006183624,
  -0.0014895147178322077,
  0.002729653613641858,
  -0.04564250633120537,
  0.01430203765630722,
  0.03857910633087158,
  -0.019303033128380775,
  -0.006588238291442394,
  0.022282062098383904,
  -0.015056904405355452,
  0.01147802546620369,
  -0.0040810005739331245,
  0.02681126445531845,
  0.0021752980537712574,
  0.032674964517354965,
  -0.022160744294524193,
  -0.016903633251786232,
  0.019869182258844376,
  0.020556651055812836,
  -0.007919365540146828,
  -0.01612180657684803,
  -0.07122711092233658,
  -0.004145029932260513,
  -0.005011104978621006,
  -0.035451799631118774,
  0.03863302618265152,
  -0.003565399441868067,
  -0.06378627568483353,
  -0.002729653613641858,
  -0.01641836203634739,
  0.0013968412531539798,
  0.03472389280796051,
  -0.01021092664450407,
  -0.017995495349168777,
  0.026622548699378967,
  0.009058406576514244,
  0.013385413214564323,
  -0.0050751338712871075,
  -0.03779727965593338,
  -0.006389411631971598,
  0.031084353104233745,
  -0.030679959803819656,
  0.013176476582884789,
  0.010231146588921549,
  -0.011848718859255314,
  -0.003236830001696944,
  0.03483172878623009,
  0.003659758018329739,
  -0.017119308933615685,
  0.0294667799025774,
  -0.03779727965593338,
  -0.023441322147846225,
  0.080609031021595,
  0.022875171154737473,
  -0.011592603288590908,
  0.018561644479632378,
  -0.0119902566075325,
  0.03998100012540817,
  -0.026325993239879608,
  0.03146178647875786,
  -0.010150267742574217,
  0.00855291448533535,
  0.04701744392514229,
  0.04734095558524132,
  0.01314951665699482,
  -0.06637439131736755,
  -0.02057013101875782,
  0.03359159082174301,
  0.0016049352707341311,
  0.00052234111353755,
  0.022619055584073067,
  -0.045777302235364914,
  0.044321488589048386,
  0.03782423958182335,
  0.00695556215941906,
  0.035694435238838196,
  0.01964002661406994,
  0.014369436539709568,
  -0.046828724443912506,
  0.02101496420800686,
  0.03027556650340557,
  0.005139162763953209,
  -2.0746210793731738e-05,
  -0.02782224863767624,
  -0.026164235547184944,
  -0.01782025769352913,
  -0.014558153226971626,
  -0.041517697274684906,
  0.006500619929283857,
  -0.018885159865021706,
  0.012462048791348934,
  0.00392598332837224,
  0.002633610274642706,
  -0.024398386478424072,
  0.030706919729709625,
  -0.03259408846497536,
  0.008384417742490768,
  0.036799777299165726,
  -0.009307782165706158,
  -0.030679959803819656,
  0.00792610552161932,
  0.0011474655475467443,
  -0.00380466552451253,
  -0.03644930198788643,
  -0.01178805995732546,
  0.02589464001357555,
  0.02367047779262066,
  -0.020704928785562515,
  0.004963926039636135,
  0.036611057817935944,
  -0.007993504405021667,
  0.01976134441792965,
  -0.01531301997601986,
  0.028577115386724472,
  -0.040466275066137314,
  -0.023333484306931496,
  0.03728504851460457,
  -0.002923425519838929,
  0.006369192153215408,
  -0.02013877779245377,
  -0.005988388322293758,
  0.041275061666965485,
  -0.01025810558348894,
  -0.009563897736370564,
  0.023576119914650917,
  -5.771027281298302e-05,
  0.050225626677274704,
  0.05292158201336861,
  -0.01602744869887829,
  0.008525955490767956,
  0.009954811073839664,
  0.042137764394283295,
  0.02253817766904831,
  -0.005964798852801323,
  0.011275828815996649,
  0.024020953103899956,
  0.03968444839119911,
  0.03092259541153908,
  0.010298545472323896,
  0.0020236505661159754,
  -0.04774535074830055,
  -0.003740636631846428,
  0.047098319977521896,
  0.0017894397024065256,
  0.011929597705602646,
  -0.01955914869904518,
  0.028550155460834503,
  0.004670740570873022,
  -0.08389809727668762,
  0.000846276874653995,
  -0.016634037718176842,
  -0.009793054312467577,
  -0.011579123325645924,
  0.035128284245729446,
  0.06384019553661346,
  0.0024448935873806477,
  -0.03005989082157612,
  -0.0028543416410684586,
  0.026460791006684303,
  0.05974234640598297,
  -0.01013678777962923,
  -0.027188699692487717,
  0.04289263114333153,
  0.0143424766138196,
  0.02833447977900505,
  0.005890659987926483,
  0.06421763449907303,
  -2.859185951820109e-05,
  -0.005661503877490759,
  0.00385521468706429,
  0.028846710920333862,
  0.08772635459899902,
  0.013587609864771366,
  -0.08125606179237366,
  0.02540936879813671,
  -0.010170487686991692,
  -0.024546664208173752,
  0.04327006638050079,
  -0.05564449727535248,
  0.0022005727514624596,
  -0.03035644441843033,
  0.02431750670075417,
  0.08373633772134781,
  -0.01419419888406992,
  0.013196696527302263,
  -0.06125207990407944,
  0.027930086478590965,
  -0.048769813030958176,
  0.009280822239816189,
  -0.03731200844049454,
  -0.03170442208647728,
  0.03593707084655762,
  -0.011161250993609428,
  -0.01325735542923212,
  0.004397775512188673,
  0.016701437532901764,
  0.05844828858971596,
  -0.00448539387434721,
  0.015366939827799795,
  -0.02621815539896488,
  0.01344607211649418,
  0.007535192184150219,
  0.04286567121744156,
  -0.025962039828300476,
  -0.08778027445077896,
  0.013115817680954931,
  -0.002746503334492445,
  -0.023023448884487152,
  -0.03496652841567993,
  -0.023293044418096542,
  0.0035384399816393852,
  0.014167239889502524,
  -0.005078503862023354,
  -0.013843725435435772,
  -0.03992708399891853,
  -0.021837228909134865,
  -0.015690453350543976,
  -0.021095842123031616,
  0.008842729963362217,
  0.01259684655815363,
  0.004825758282095194,
  -0.005135792773216963,
  0.01502994541078806,
  0.021419357508420944,
  0.006065897177904844,
  -0.044591084122657776,
  0.041032422333955765,
  -0.04386317729949951,
  0.020799286663532257,
  -0.011889158748090267,
  -0.011518464423716068,
  -0.04383621737360954,
  -0.003845104714855552,
  -0.03167746216058731,
  0.015191702172160149,
  0.010116568766534328,
  -0.006217544432729483,
  -0.005311029963195324,
  0.01337193325161934,
  -0.02015225775539875,
  -0.04170641303062439,
  0.02763353101909161,
  -0.023158246651291847,
  0.014814268797636032,
  -0.013129297643899918,
  -0.02674386650323868,
  0.02145979553461075,
  -0.010190707631409168,
  -0.017537182196974754,
  -0.008579874411225319,
  0.0014473904157057405,
  -0.0018635784508660436,
  0.026137277483940125,
  0.0024432085920125246,
  -0.003848474705591798,
  0.02887367084622383,
  -0.009644776582717896,
  0.03469693288207054,
  0.05065698176622391,
  0.0010084554087370634,
  -0.01259684655815363,
  0.002015225822106004,
  -0.08012375980615616,
  0.04874285310506821,
  -0.03445429727435112,
  0.0063354927115142345,
  0.003696827217936516,
  -0.01469295099377632,
  -0.01695755310356617,
  -0.031515706330537796,
  -0.02970941551029682,
  -0.022052906453609467,
  0.02005789987742901,
  -0.028469277545809742,
  -0.03990012407302856,
  0.06195303052663803,
  0.02569244429469109,
  -0.008667493239045143,
  0.0406549908220768,
  0.0008812400628812611,
  -0.05143880844116211,
  0.010601839981973171,
  0.035155244171619415,
  -0.002692584414035082,
  0.047394875437021255,
  0.06486465781927109,
  -0.027471773326396946,
  -0.010143527761101724,
  0.022376419976353645,
  0.03644930198788643,
  0.01602744869887829,
  -0.005135792773216963,
  -0.03146178647875786,
  -0.009873932227492332,
  0.04647825285792351,
  0.009031446650624275,
  0.03857910633087158,
  -0.019693946465849876,
  0.0006659849314019084,
  -0.0126440254971385,
  -0.014288557693362236,
  -0.014531193301081656,
  -0.008546175435185432,
  0.021473275497555733,
  0.028496237471699715,
  -0.005715423263609409,
  0.01162630319595337,
  0.0003553183632902801,
  0.02017921768128872,
  0.016324002295732498,
  -0.028010964393615723,
  -0.030706919729709625,
  -0.004259607754647732,
  -0.01325735542923212,
  0.015366939827799795,
  -0.01210483442991972,
  0.005974908825010061,
  0.0027347085997462273,
  0.014517713338136671,
  0.0024735380429774523,
  -0.0013033254072070122,
  0.041302017867565155,
  0.008620313368737698,
  0.01558261550962925,
  0.02346828207373619,
  0.006028827745467424,
  0.0013513470767065885,
  0.05273286625742912,
  -0.032432328909635544,
  -0.01028506550937891,
  0.028226641938090324,
  -0.01985570415854454,
  0.004138289950788021,
  0.018143773078918457,
  0.03677281737327576,
  -0.012307031080126762,
  0.017806777730584145,
  0.01796853542327881,
  -0.02519369311630726,
  0.018709922209382057,
  0.012313771061599256,
  0.007818267680704594,
  -0.014895147643983364,
  0.01746978424489498,
  0.004188838880509138,
  0.011841978877782822,
  -0.019087355583906177,
  -0.015919610857963562,
  0.036826737225055695,
  0.04553466662764549,
  -0.006982521619647741,
  0.0122531121596694,
  -0.01919519528746605,
  0.02145979553461075,
  -0.00354854972101748,
  -0.03148874640464783,
  0.02131151780486107,
  0.019788304343819615,
  -0.049335964024066925,
  0.0509265772998333,
  0.010992753319442272,
  0.001618415000848472,
  0.045777302235364914,
  0.00814852211624384,
  -0.02062405087053776,
  -0.00286276638507843,
  0.016728395596146584,
  0.016620557755231857,
  0.014868187718093395,
  -0.010197446681559086,
  -0.03369942680001259,
  -0.008721412159502506,
  0.04720615968108177,
  0.00771042937412858,
  0.012832742184400558,
  0.03332199528813362,
  0.020044419914484024,
  -0.006268093828111887,
  0.02030053548514843,
  0.06491857767105103,
  0.0437014177441597,
  0.03981924429535866,
  0.02346828207373619,
  0.005745752714574337,
  -0.02708085998892784,
  0.013992003165185452,
  0.014908627606928349,
  -2.1654515876434743e-05,
  0.012590106576681135,
  -0.006699446588754654,
  -0.01337193325161934,
  0.01570393331348896,
  0.018319008871912956,
  -0.006008608266711235,
  0.03663801774382591,
  0.03480476886034012,
  -0.033807266503572464,
  0.011262348853051662,
  0.038767822086811066,
  0.0013513470767065885,
  -0.024910617619752884,
  -0.021621553227305412,
  -0.002822327194735408,
  0.024641022086143497,
  -0.007130798883736134,
  0.0011609452776610851,
  0.0144503153860569,
  0.01848076656460762,
  0.01868296228349209,
  0.006520839408040047,
  0.03841734677553177,
  -0.004741509445011616,
  0.03820167109370232,
  -0.03345679119229317,
  -0.004188838880509138,
  0.01040638331323862,
  -0.0027010091580450535,
  -0.01934347115457058,
  0.0007957277703098953,
  -0.022915611043572422,
  -0.042137764394283295,
  -0.0036900874692946672,
  -0.044051893055438995,
  -0.029574617743492126,
  -0.03426557779312134,
  -0.04930900409817696,
  0.013621308840811253,
  0.006706186104565859,
  0.008680973201990128,
  0.018440326675772667,
  -0.04356662184000015,
  0.037985995411872864,
  -0.05162752419710159,
  0.0032048155553638935,
  -0.008182221092283726,
  0.011828499846160412,
  0.018494246527552605,
  -0.003882174147292971,
  -0.04610081762075424,
  0.008054163306951523,
  -0.005176232196390629,
  -0.03135394677519798,
  0.050198670476675034,
  0.032674964517354965,
  -0.10179923474788666,
  -0.004417994990944862,
  0.014665991067886353,
  -0.009678475558757782,
  -0.006298423279076815,
  0.0006171207642182708,
  0.01531301997601986,
  -0.03674585744738579,
  0.035128284245729446,
  0.047718390822410583,
  0.0020287055522203445,
  -0.025274571031332016,
  0.017510222271084785,
  -0.03814775124192238,
  -0.03132699057459831,
  -0.008883168920874596,
  0.06146775931119919,
  -0.024735379964113235,
  -9.409512131242082e-05,
  -0.0033345583360642195,
  0.019653506577014923,
  0.05106137320399285,
  0.01469295099377632,
  -0.028442317619919777,
  0.01818421110510826,
  -0.017146268859505653,
  -0.007191458251327276,
  -0.03529004007577896,
  0.026973022148013115,
  -0.040681950747966766,
  0.014126800000667572,
  -0.036260586231946945,
  0.000831533398013562,
  0.0012173918075859549,
  0.012010476551949978,
  0.0018214541487395763,
  0.017631540074944496,
  0.00179280957672745,
  -0.011147771030664444,
  0.027849208563566208,
  -0.0007451786077581346,
  0.0006617725011892617,
  -0.04472588002681732,
  0.03636842221021652,
  0.02513977326452732,
  -0.011302788741886616,
  -0.003740636631846428,
  -0.017577622085809708,
  -0.010177227668464184,
  -0.02376483753323555,
  0.03987316414713859,
  0.02976333536207676,
  0.006156885530799627,
  -0.02838839776813984,
  0.05618368834257126,
  0.00549300666898489,
  -0.019235633313655853,
  0.03469693288207054,
  0.007757608313113451,
  0.006251243874430656,
  -0.02391311526298523,
  0.06933994591236115,
  -0.007663249969482422,
  0.006392781622707844,
  -0.00538853881880641,
  0.02941286191344261,
  -0.03674585744738579,
  -0.003696827217936516,
  -0.04399797320365906,
  -0.007589111104607582,
  -0.0186290442943573,
  -0.03928005322813988,
  -0.009402140974998474,
  8.319546395796351e-06,
  0.024250108748674393,
  -0.010426603257656096,
  0.00992785207927227,
  -0.02222814224660397,
  -0.06874683499336243,
  -0.014396395534276962,
  0.004714549984782934,
  0.011707181110978128,
  -0.02519369311630726,
  -0.01135670766234398,
  0.014140279963612556,
  -0.024978015571832657,
  0.008188961073756218,
  0.01600048877298832,
  0.032297533005476,
  -0.05580625310540199,
  0.004967295564711094,
  0.016431841999292374,
  0.014665991067886353,
  -0.004054041113704443,
  0.002783572766929865,
  0.003014413872733712,
  -0.01013678777962923,
  0.01295405998826027,
  0.03475084900856018,
  -0.004711179994046688,
  0.030437324196100235,
  -0.017847217619419098,
  -0.0051155732944607735,
  -0.010467042215168476,
  0.03901045769453049,
  0.007393654435873032,
  0.012711424380540848,
  0.014045922085642816,

In [15]:
# Obtain all data in DataFrame
cursor = collection.find({}, {"_id": 0})
df = pd.DataFrame(cursor)

### Neo4j

In [16]:
driver = neo4j.GraphDatabase.driver(
    uri=os.environ.get("NEO4J_URI"), 
    auth=(os.environ.get("NEO4J_USERNAME"), 
          os.environ.get("NEO4J_PASSWORD"))
)

In [17]:
session = driver.session(database="neo4j")

In [18]:
def my_neo4j_run_query_pandas(query, **kwargs):
    "run a query and return the results in a pandas dataframe"
    
    result = session.run(query, **kwargs)
    
    df = pd.DataFrame([r.values() for r in result], columns=result.keys())
    
    return df

In [19]:
def my_neo4j_create_node(node_label, node_name):
    "create a node with label node_type"

    # Note1: Cannot use parameter in labels (so, use f-string, instead).
    #        When using f-string, need to double {} when using it as a part of Cypher.
    # Note2: Merge: Create if not exists, otherwise reuse
    query = f"""
    
    MERGE (:{node_label} {{name: $node_name}})
    
    """
    
    session.run(query, node_name=node_name)

In [20]:
# Create constraints
query = """
CREATE CONSTRAINT company_name_unique IF NOT EXISTS
FOR (c:Company)
REQUIRE c.name IS UNIQUE;
"""

session.run(query)

# Add Company nodes and relationship

In [21]:
# Create nodes
for document in collection.find():
    company = document.get("company")
    my_neo4j_create_node("Company", company)

In [22]:
# Create relationships
for document in collection.find():

    from_node = document.get("complaint_id")   # This is a Complaint node
    to_node = document.get("company")          # This is a Company node
    weight = 1
    
    query = """
    
    MATCH (from: Complaint), 
          (to: Company)
    WHERE from.complaint_id = $from_node and to.name = $to_node
    MERGE (from)-[:COMPLAIN_TO {weight: $weight}]->(to)
    
    """

    session.run(query, {"from_node":from_node, "to_node":to_node, "weight":weight})

# Add Relationship between Company and Categories

In [23]:
query = """
MATCH (corp:Company)<-[:COMPLAIN_TO]-(comp:Complaint)
    -[:IN_CATEGORY]->(cat:Category)

// Note:
// - pairCount: Number of complaints
WITH corp, cat,
     count(comp) AS pairCount

MERGE (cat)-[r:COMPLAINS_TO]->(corp)
SET r.num = pairCount;

"""

session.run(query)

In [24]:
# Drop the in-memory graph
query = "CALL gds.graph.drop('ds_graph', false) yield graphName"
session.run(query)

# Create an in-memory graph named 'ds_graph'
# Nodes: Category, Company
# Relationship: COMPLAINS_TO, weighted by r.num
query = """
CALL gds.graph.project(
    'ds_graph', 
    ['Category', 'Company'], 
    {
        COMPLAINS_TO: {
            type: 'COMPLAINS_TO', 
            orientation: 'NATURAL',
            properties: 'num'
        }
    }
)
"""

session.run(query)

### Company Counts

In [25]:
Company_counts = df['company'].value_counts()
print(Company_counts)

company
TRANSUNION INTERMEDIATE HOLDINGS, INC.                                           69
EQUIFAX, INC.                                                                    65
Experian Information Solutions Inc.                                              61
CITIBANK, N.A.                                                                    3
CAPITAL ONE FINANCIAL CORPORATION                                                 3
Resurgent Capital Services L.P.                                                   3
Chime Financial Inc                                                               3
CL Holdings LLC                                                                   2
MOHELA                                                                            2
BANK OF AMERICA, NATIONAL ASSOCIATION                                             2
I.C. System, Inc.                                                                 2
WELLS FARGO & COMPANY                                                             2
WEBSTER BANK, NATIONAL ASSOCIATION                                                1
TRANSWORLD SYSTEMS INC                                                            1
FAIR COLLECTIONS & OUTSOURCING, INC.                                              1
Paypal Holdings, Inc                                                              1
AMERICAN EXPRESS COMPANY                                                          1
Oliphant United, Inc.                                                             1
ENCORE CAPITAL GROUP INC.                                                         1
Ray Klein, Inc.                                                                   1
Velocity Portfolio Group                                                          1
Prince Parker & Associates                                                        1
T.S. Holdings                                                                     1
Kriya Capital, LLC                                                                1
Clasp Group, Inc.                                                                 1
National Commercial Services, Inc                                                 1
Coinbase, Inc.                                                                    1
American Profit Recovery, Inc., Marlborough, MA Branch                            1
Southern Auto Finance Co                                                          1
FISERV INC.                                                                       1
SinglePoint GI                                                                    1
Community Loan Servicing, LLC (formerly known as Bayview Loan Servicing, LLC)     1
SYNCHRONY FINANCIAL                                                               1
Solar Mosaic LLC                                                                  1
Fig Tech Inc.                                                                     1
Portfolio Recovery Associates, LLC                                                1
ROBINHOOD MARKETS INC.                                                            1
HYUNDAI CAPITAL AMERICA                                                           1
Avant Holding Company, Inc.                                                       1
Lendmark Financial Services                                                       1
GOLDMAN SACHS BANK USA                                                            1
DriveTime                                                                         1
Bread Financial Holdings, Inc.                                                    1
U.S. BANCORP                                                                      1
Mr. Cooper Group Inc.                                                             1
Name: count, dtype: int64

### Degree Centrality

In [26]:
# Note: 'UNDIRECTED': Count both in and out going arrows
query = """
CALL gds.degree.stream(
    'ds_graph',
    {orientation: 'UNDIRECTED'}
)
YIELD nodeId, score
WITH gds.util.asNode(nodeId) AS n, score
WHERE n:Company
RETURN n.name AS Company, score AS Degree
ORDER BY Degree DESC, Company;
"""

my_neo4j_run_query_pandas(query).head(10)
# session.run(query)

                                  Company  Degree
0                           EQUIFAX, INC.    10.0
1  TRANSUNION INTERMEDIATE HOLDINGS, INC.     9.0
2     Experian Information Solutions Inc.     8.0
3       CAPITAL ONE FINANCIAL CORPORATION     3.0
4                          CITIBANK, N.A.     2.0
5                         CL Holdings LLC     2.0
6                       I.C. System, Inc.     2.0
7         Resurgent Capital Services L.P.     2.0
8                   WELLS FARGO & COMPANY     2.0
9                AMERICAN EXPRESS COMPANY     1.0

# Louvain

In [27]:
# Get the results from the Louvain community detection algorithm stored in DataFrame
query = """

CALL gds.louvain.stream(
    'ds_graph',
    {
        includeIntermediateCommunities: true,
        relationshipWeightProperty: 'num'
    }
)
YIELD nodeId, communityId, intermediateCommunityIds
WITH gds.util.asNode(nodeId) AS n, communityId, intermediateCommunityIds
WHERE n:Company
RETURN 
    n.name AS company,
    communityId AS community,
    intermediateCommunityIds AS intermediate_community
ORDER BY community, company

"""

community_df = my_neo4j_run_query_pandas(query)

In [28]:
community_df.head(20)

,company,community,intermediate_community
0,SinglePoint GI,15,"[15, 15, 15, 15]"
1,"Community Loan Servicing, LLC (formerly known ...",16,"[16, 16, 16, 16]"
2,"CITIBANK, N.A.",17,"[13, 13, 13, 17]"
3,Resurgent Capital Services L.P.,17,"[24, 24, 13, 17]"
4,SYNCHRONY FINANCIAL,17,"[17, 17, 17, 17]"
5,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",17,"[10, 24, 13, 17]"
6,Solar Mosaic LLC,18,"[18, 18, 18, 18]"
7,Fig Tech Inc.,19,"[19, 19, 19, 19]"
8,WELLS FARGO & COMPANY,22,"[22, 22, 22, 22]"
9,"Portfolio Recovery Associates, LLC",23,"[23, 23, 23, 23]"
10,FISERV INC.,25,"[25, 25, 25, 25]"
11,ROBINHOOD MARKETS INC.,26,"[26, 26, 26, 26]"
12,"Avant Holding Company, Inc.",27,"[27, 27, 27, 27]"
13,Lendmark Financial Services,29,"[29, 29, 29, 29]"
14,GOLDMAN SACHS BANK USA,30,"[30, 30, 30, 30]"
15,DriveTime,31,"[31, 31, 31, 31]"
16,"Bread Financial Holdings, Inc.",33,"[33, 33, 33, 33]"
17,U.S. BANCORP,34,"[34, 34, 34, 34]"
18,HYUNDAI CAPITAL AMERICA,35,"[35, 35, 35, 35]"
19,Southern Auto Finance Co,36,"[36, 36, 36, 36]"

In [29]:
# Write back the results of the Louvain to Knowledge Graph
# (Community ID)

query = """

CALL gds.louvain.write(
    'ds_graph',
    {
        includeIntermediateCommunities: false,
        relationshipWeightProperty: 'num',
        writeProperty: 'community_id'
    }
)
YIELD communityCount, nodePropertiesWritten

"""

session.run(query)

In [30]:
# Write back the results of the Louvain to Knowledge Graph
# (Intermediate Community ID)

query = """

CALL gds.louvain.write(
    'ds_graph',
    {
        includeIntermediateCommunities: true,
        relationshipWeightProperty: 'num',
        writeProperty: 'intermediate_community'
    }
)
YIELD communityCount, nodePropertiesWritten

"""

session.run(query)

In [31]:
# Add properties to Complaint nodes based on Companies' community ID

query = """
MATCH (comp:Complaint)-[:COMPLAIN_TO]->(corp:Company)

SET
    comp.corp_community_id = corp.community_id,
    comp.corp_intermediate_community = corp.intermediate_community

RETURN count(comp) AS complaintsUpdated;

"""

session.run(query)

In [32]:
# Timestamp (End)
current_datetime = datetime.now()
formatted_time = current_datetime.strftime("%Y-%m-%d_%H:%M:%S")
print(formatted_time)

end_time = time.time()
elapsed_seconds = end_time - start_time

# Convert elapsed seconds to minutes and seconds
minutes = int(elapsed_seconds // 60)
seconds = elapsed_seconds % 60

print(f"Program elapsed time: {minutes} minutes and {seconds:.2f} seconds")

2026-01-08_22:23:37
Program elapsed time: 0 minutes and 3.43 seconds